const express = require('express');
const http = require('http');
const path = require('path');
const { Server } = require('socket.io');

const app = express();
const server = http.createServer(app);
const io = new Server(server);

app.use(express.static('public'));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'quiz.html'));
});

app.get('/manifest.json', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'manifest.json'));
});

let quizSessions = {};
let kahootGames = {};

const ecFullQuestions = [
  {q:"Which topic focuses on an individual's thoughts, feelings, and experiences?",a:["Social topic","Personal topic","Cultural topic","Public topic"],c:1},
  {q:"Which topic involves communication between two or more people?",a:["Personal topic","Interpersonal topic","Social topic","Academic topic"],c:1},
  {q:"Which refers to the words and sentence structure used in communication?",a:["Tone","Language","Context","Purpose"],c:1},
  {q:"What does tone refer to?",a:["The speaker's attitude or feeling","The audience","The topic","The grammar"],c:0},
  {q:"Which refers to the reason for communicating?",a:["Audience","Purpose","Context","Tone"],c:1},
  {q:"Who is the receiver of a message?",a:["Purpose","Audience","Context","Language"],c:1},
  {q:"Which refers to the situation in which communication takes place?",a:["Tone","Context","Audience","Purpose"],c:1},
  {q:"What is the main point of a text?",a:["A supporting detail","The central idea or message","An example","A conclusion"],c:1},
  {q:"Which is usually a supporting detail?",a:["A fact or example","The title","The conclusion","The main point"],c:0},
  {q:"What is noise in communication?",a:["Important supporting details","Unnecessary information that distracts from the main message","The main point","The title"],c:1},
  {q:"Which type of text combines words, images, audio, and videos?",a:["Spoken text","Written text","Multimodal text","Narrative text"],c:2},
  {q:"Which is an example of a spoken text?",a:["Podcast","Essay","Infographic","Poster"],c:0},
  {q:"Why is it important to match language and tone with the audience?",a:["To make the message longer","To communicate the message effectively","To sound intelligent","To avoid using examples"],c:1},
  {q:"Why are supporting details important?",a:["They replace the main point.","They explain and strengthen the main point.","They confuse the audience.","They summarize the entire text."],c:1},
  {q:"Why is identifying the main point important?",a:["It helps readers understand the author's message.","It changes the author's opinion.","It increases the length of the text.","It removes supporting details."],c:0},
  {q:'Why should listeners pay attention to signposts such as "To summarize..."?',a:["They introduce jokes.","They signal important ideas.","They announce the speaker.","They give examples only."],c:1},
  {q:"Why is the title helpful in a written text?",a:["It gives supporting details.","It introduces the topic.","It explains every paragraph.","It summarizes the conclusion."],c:1},
  {q:"Why should readers ignore noise?",a:["It changes the author's message.","It is not essential to understanding the main point.","It contains the main idea.","It is always false."],c:1},
  {q:"Your teacher asks you to write a letter to the principal. Which tone should you use?",a:["Casual","Humorous","Formal","Angry"],c:2},
  {q:'Which sentence best supports the main point, "Exercise improves health"?',a:["Exercise strengthens the heart.","I bought new shoes yesterday.","My favorite color is blue.","My brother likes basketball."],c:0},
  {q:"While listening to a speech, which strategy will best help you identify the speaker's main point?",a:["Memorize every sentence.","Listen for signposts.","Count the number of paragraphs.","Ignore the conclusion."],c:1},
  {q:"Which should you examine to determine the main point of an infographic?",a:["Images only","Text only","Text, images, and graphics together","Background color only"],c:2},
  {q:"Your friend tells you about a personal problem. Which response best demonstrates interpersonal communication?",a:["Ignore the problem.","Listen carefully and give respectful advice.","Change the topic immediately.","Laugh at the situation."],c:1},
  {q:"Which situation best demonstrates communicative flexibility?",a:["Using the same language with everyone","Changing language and tone depending on the audience","Speaking formally in every situation","Avoiding communication with strangers"],c:1},
  {q:"Read the paragraph. Reading books improves learning. It builds vocabulary. My backpack is blue. It develops critical thinking. Which sentence is noise?",a:["Reading books improves learning.","It builds vocabulary.","My backpack is blue.","It develops critical thinking."],c:2},
  {q:"Read the paragraph. Many students stay up late using their phones. They often feel sleepy in class. Using smartphones responsibly helps students perform better in school. Which sentence is the main point?",a:["Many students stay up late using their phones.","They often feel sleepy in class.","Using smartphones responsibly helps students perform better in school.","Students use smartphones every day."],c:2},
  {q:'Which pair of sentences best supports the main point, "Technology improves communication"? 1. It allows instant messaging. 2. It helps people communicate across long distances. 3. My phone case is black. 4. I enjoy watching movies.',a:["1 and 2","1 and 3","2 and 4","3 and 4"],c:0},
  {q:"Which paragraph is most effective in communicating its main point?",a:["A paragraph with one clear main point supported by relevant details.","A paragraph with several unrelated ideas.","A paragraph with no supporting details.","A paragraph that changes topics in every sentence."],c:0},
  {q:'Which supporting detail best strengthens the statement, "Recycling helps protect the environment"?',a:["Recycling reduces waste sent to landfills.","My recycling bin is blue.","I recycled yesterday.","Recycling trucks are large."],c:0},
  {q:"A student gives a presentation with a clear main point, relevant supporting details, and no unnecessary information. How would you evaluate the presentation?",a:["It is effective because the ideas are clear and well-supported.","It needs more unrelated stories.","It should contain less supporting evidence.","It is ineffective because it focuses on one main idea."],c:0}
];

const milFullQuestions = [
  {q:"Which communication model answers the question, \"Who says what, in which channel, to whom, with what effect?\"",a:["Berlo's SMCR Model","Lasswell's Communication Model","Schramm's Communication Model","Shannon-Weaver Communication Model"],c:1},
  {q:"Which communication model is known as the SMCR Model?",a:["Lasswell's Communication Model","Shannon-Weaver Communication Model","Berlo's Communication Model","Westley and MacLean's Communication Model"],c:2},
  {q:"Which communication model first introduced noise as a factor affecting communication?",a:["Lasswell's Communication Model","Schramm's Communication Model","Berlo's Communication Model","Shannon-Weaver Communication Model"],c:3},
  {q:"Which communication model emphasizes feedback and a shared field of experience?",a:["Berlo's Communication Model","Shannon-Weaver Communication Model","Schramm's Communication Model","Lasswell's Communication Model"],c:2},
  {q:"Which communication model highlights the role of gatekeepers in mass communication?",a:["Berlo's Communication Model","Westley and MacLean's Communication Model","Lasswell's Communication Model","Schramm's Communication Model"],c:1},
  {q:"What is the ability to read, understand, evaluate, and use information effectively?",a:["Communication","Empowerment","Literacy","Technology"],c:2},
  {q:"What is the process of becoming stronger and more confident in controlling one's life?",a:["Communication","Information","Empowerment","Literacy"],c:2},
  {q:"Which term refers to facts, data, or knowledge learned about something or someone?",a:["Literacy","Information","Technology","Communication"],c:1},
  {q:"Which best describes the Internet?",a:["A collection of websites connected through hyperlinks","A unique address assigned to every website","A global network connecting computers and electronic devices","A collection of domain names"],c:2},
  {q:"Which best describes the World Wide Web?",a:["A global network of interconnected computers","A collection of websites accessible through the Internet","A system that assigns IP addresses to websites","A service for registering domain names"],c:1},
  {q:"What is a domain name?",a:["The software used to browse websites","The unique name used to identify a website","The collection of web pages on the Internet","The network connecting computers worldwide"],c:1},
  {q:"Which Top-Level Domain (TLD) is commonly used by commercial businesses?",a:[".edu",".gov",".org",".com"],c:3},
  {q:"How does the Internet differ from the World Wide Web?",a:["The Internet stores websites, while the Web connects computers.","The Internet provides the network, while the Web contains websites and web pages.","The Internet and the World Wide Web are different names for the same technology.","The Web manages domain names, while the Internet manages IP addresses."],c:1},
  {q:"Why is literacy considered the foundation of empowerment?",a:["Literacy helps people make informed decisions using accurate information.","Literacy allows people to register websites and domain names.","Literacy enables people to connect devices to the Internet.","Literacy makes communication faster than technology."],c:0},
  {q:"Why is a domain name more practical than an IP address for most users?",a:["Domain names automatically improve website security.","Domain names are easier to remember than numerical IP addresses.","Domain names eliminate the need for web browsers.","Domain names replace the Internet when accessing websites."],c:1},
  {q:"Why are scholarly publications generally considered more reliable than popular publications?",a:["They are written using simpler language.","They undergo expert review before publication.","They are published more frequently.","They are intended for all readers."],c:1},
  {q:"How does a trade publication differ from a scholarly publication?",a:["Trade publications present original research, while scholarly publications provide industry news.","Trade publications target professionals in a specific field, while scholarly publications report academic research.","Trade publications are written for the general public, while scholarly publications target professionals.","Trade publications are reviewed only by government agencies."],c:1},
  {q:"Why is feedback important in Schramm's Communication Model?",a:["It replaces the original message with a new one.","It allows both participants to determine whether the message was understood.","It prevents noise from affecting communication.","It ensures the sender always agrees with the receiver."],c:1},
  {q:"Your teacher asks you to cite information about climate change in a research paper. Which source is most appropriate?",a:["A personal blog discussing opinions about climate change","A scholarly journal containing peer-reviewed studies","A social media post shared by several users","An entertainment magazine featuring celebrity interviews"],c:1},
  {q:"A newly opened bakery wants customers to remember its website easily. Which should the owner obtain first?",a:["A web browser","A domain name","A search engine","A modem"],c:1},
  {q:"A student wants to visit www.deped.gov.ph. Which component helps the student identify the website instead of typing its numerical IP address?",a:["Web browser","Domain name","Search engine","World Wide Web"],c:1},
  {q:"While presenting in class, Maria smiles, maintains eye contact, and speaks clearly. Which combination of communication types is she using?",a:["Oral and Written","Written and Nonverbal","Oral and Nonverbal","Written and Visual"],c:2},
  {q:"A university plans to publish the results of a scientific experiment for researchers worldwide. Which source is the best choice?",a:["Popular publication","Trade publication","Scholarly publication","Social media page"],c:2},
  {q:"A teacher wants students to learn how to repair a computer by watching demonstrations. Which format of information is most suitable?",a:["Print format","Graphic format","Audio and Video format","Statistical format"],c:2},
  {q:"A student claims that the Internet and the World Wide Web are the same because both allow access to websites. Which statement best analyzes this claim?",a:["The claim is correct because websites exist only on the Internet.","The claim is incorrect because the Internet is the network, while the Web is one of its services.","The claim is correct because both terms refer to web browsers.","The claim is incorrect because websites do not require the Internet."],c:1},
  {q:"A website ends with .org, but it contains misleading health information without references. What should you conclude?",a:["The website is reliable because of its domain.","The domain alone cannot determine the credibility of the information.","All .org websites are nonprofit and therefore trustworthy.","Websites with .org domains are reviewed by government agencies."],c:1},
  {q:"A student uses only one website as a reference for an important research project. Which weakness is most evident?",a:["The student selected the wrong domain.","The student failed to verify information using multiple credible sources.","The student should have used only printed books.","The student relied too much on nonverbal communication."],c:1},
  {q:"You discover that two websites provide conflicting medical advice. What is the best course of action?",a:["Accept the information from the website with more advertisements.","Compare the information with scholarly or government sources before deciding.","Follow the website that appears first in the search results.","Share both websites so others can decide."],c:1},
  {q:"Your school needs to announce an emergency evacuation to all students immediately. Which communication channel is most effective?",a:["Printed newsletters","Public address system","School website","Classroom bulletin board"],c:1},
  {q:"A social media post claims that drinking a certain herbal tea cures all diseases but provides no evidence or author. What is the best response?",a:["Share the post because many people reacted to it.","Accept the claim until proven false.","Verify the information using reliable and credible sources before believing or sharing it.","Ignore all information found on social media."],c:2}
];

function shuffleArray(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function generateCode(){return Math.floor(1000+Math.random()*9000).toString();}
function getScores(code){return Object.entries(quizSessions[code].players).map(([id,p])=>({...p,id:id})).sort((a,b)=>b.score-a.score);}
function getQuestionTexts(subject){const qs=subject==='ec'?ecFullQuestions:shuffleArray(milFullQuestions).slice(0,30);return qs.map(q=>q.q);}
function getFullQuestions(subject){if(subject==='ec')return ecFullQuestions;return shuffleArray(milFullQuestions).slice(0,30);}

io.on('connection',(socket)=>{
  socket.on('quiz-create-session',(data)=>{const code=generateCode();quizSessions[code]={players:{},subject:data.subject||'mil',timer:data.timer||0,hostSocket:socket.id,started:false,questionTexts:getQuestionTexts(data.subject),studentQuestions:{}};socket.join(`quiz-host-${code}`);socket.quizCode=code;socket.isQuizHost=true;socket.emit('quiz-session-created',{code,subject:data.subject,timer:data.timer,totalQuestions:30});});
  socket.on('quiz-start',(data)=>{const code=data.code||socket.quizCode;if(!code||!quizSessions[code])return;quizSessions[code].started=true;Object.keys(quizSessions[code].players).forEach(id=>{if(!quizSessions[code].players[id].waitingForApproval)io.to(id).emit('quiz-started',{subject:quizSessions[code].subject,timer:quizSessions[code].timer});});});
  socket.on('quiz-join',(data)=>{const{code,name}=data;if(!quizSessions[code]){socket.emit('quiz-join-error',{message:'Session not found!'});return;}const ep=Object.entries(quizSessions[code].players).find(([id,p])=>p.name===name&&id!==socket.id);if(ep){const[oid,od]=ep;if(quizSessions[code].studentQuestions[oid]){quizSessions[code].studentQuestions[socket.id]=quizSessions[code].studentQuestions[oid];delete quizSessions[code].studentQuestions[oid];}quizSessions[code].players[socket.id]={...od,loggedIn:true,waitingForApproval:true,oldSocketId:oid};delete quizSessions[code].players[oid];socket.join(`quiz-${code}`);socket.quizCode=code;socket.playerName=name;socket.emit('quiz-joined',{code,name,waiting:true});}else{socket.join(`quiz-${code}`);socket.quizCode=code;socket.playerName=name;const needsApproval=quizSessions[code].started;quizSessions[code].players[socket.id]={name,score:0,total:30,currentQuestion:0,finished:false,loggedIn:true,answering:false,answers:[],waitingForApproval:needsApproval};socket.emit('quiz-joined',{code,name,waiting:needsApproval});}io.to(`quiz-host-${code}`).emit('quiz-scores-update',{scores:getScores(code)});});
  socket.on('quiz-approve-student',(data)=>{const code=data.code||socket.quizCode,sid=data.studentId;if(!code||!quizSessions[code]||!sid)return;if(quizSessions[code].players[sid]){quizSessions[code].players[sid].waitingForApproval=false;const sq=quizSessions[code].studentQuestions[sid],p=quizSessions[code].players[sid];if(sq&&sq.length>0)io.to(sid).emit('quiz-resume',{subject:quizSessions[code].subject,timer:quizSessions[code].timer,currentQuestion:p.currentQuestion,score:p.score,answers:p.answers,questions:sq});else io.to(sid).emit('quiz-started',{subject:quizSessions[code].subject,timer:quizSessions[code].timer});}io.to(`quiz-host-${code}`).emit('quiz-scores-update',{scores:getScores(code)});});
  socket.on('quiz-reject-student',(data)=>{const code=data.code||socket.quizCode,sid=data.studentId;if(!code||!quizSessions[code]||!sid)return;if(quizSessions[code].players[sid]){io.to(sid).emit('quiz-rejected');delete quizSessions[code].players[sid];if(quizSessions[code].studentQuestions[sid])delete quizSessions[code].studentQuestions[sid];}io.to(`quiz-host-${code}`).emit('quiz-scores-update',{scores:getScores(code)});});
  socket.on('quiz-save-questions',(data)=>{const code=socket.quizCode;if(code&&quizSessions[code])quizSessions[code].studentQuestions[socket.id]=data.questions;});
  socket.on('quiz-score-update',(data)=>{const code=socket.quizCode;if(!code||!quizSessions[code])return;quizSessions[code].players[socket.id]={name:socket.playerName||data.name,score:data.score,total:30,currentQuestion:data.currentQuestion,finished:data.finished,loggedIn:true,answering:!data.finished,answers:data.answers||[],waitingForApproval:false};io.to(`quiz-host-${code}`).emit('quiz-scores-update',{scores:getScores(code)});});
  socket.on('quiz-get-scores',(data)=>{const code=data.code;if(!quizSessions[code]){socket.emit('quiz-scores-update',{scores:[]});return;}socket.emit('quiz-scores-update',{scores:getScores(code)});});
  socket.on('quiz-get-analysis',(data)=>{const code=data.code;if(!quizSessions[code]){socket.emit('quiz-analysis',{analysis:[],totalStudents:0});return;}const players=Object.values(quizSessions[code].players),ts=players.length,qt=quizSessions[code].questionTexts||[],qm={};for(let i=0;i<30;i++)qm[i]={correct:0,wrong:0,unanswered:0};players.forEach(p=>{if(p.answers&&p.answers.length>0){p.answers.forEach(a=>{if(a){const qi=a.questionId;if(qi!==undefined&&qi>=0&&qi<30&&qm[qi]){if(a.correct)qm[qi].correct++;else qm[qi].wrong++;}}});}for(let i=0;i<30;i++){if(!p.answers||!p.answers[i]||p.answers[i]===null)if(qm[i])qm[i].unanswered++;}});const a=[];for(let i=0;i<30;i++){const q=qm[i],t=q.correct+q.wrong+q.unanswered;a.push({questionNumber:i+1,questionId:i,questionText:qt[i]||`Q${i+1}`,correct:q.correct,wrong:q.wrong,unanswered:q.unanswered,total:ts,percentCorrect:t>0?Math.round((q.correct/Math.max(t,1))*100):0});}socket.emit('quiz-analysis',{analysis:a,totalStudents:ts});});
  socket.on('quiz-start-review',(data)=>{const code=data.code||socket.quizCode;if(!code||!quizSessions[code])return;quizSessions[code].reviewMode=true;quizSessions[code].reviewQuestion=0;io.to(`quiz-${code}`).emit('review-started');io.to(`quiz-host-${code}`).emit('review-started');sendReviewQ(code);});
  socket.on('quiz-next-review',(data)=>{const code=data.code||socket.quizCode;if(!code||!quizSessions[code])return;quizSessions[code].reviewQuestion++;if(quizSessions[code].reviewQuestion>=30){io.to(`quiz-${code}`).emit('review-ended');io.to(`quiz-host-${code}`).emit('review-ended');return;}sendReviewQ(code);});
  function sendReviewQ(code){const g=quizSessions[code],qi=g.reviewQuestion,qt=g.questionTexts[qi]||`Q${qi+1}`;io.to(`quiz-host-${code}`).emit('review-question',{questionNumber:qi+1,totalQuestions:30,questionText:qt});io.to(`quiz-${code}`).emit('review-question',{questionNumber:qi+1,totalQuestions:30,questionText:qt});}

  socket.on('kahoot-create',(data)=>{const pin=generateCode();if(kahootGames[pin]){socket.emit('kahoot-created',{pin:generateCode()});return;}const subject=data.subject||'mil',fullQs=getFullQuestions(subject);kahootGames[pin]={hostSocket:socket,players:{},questions:fullQs,currentQuestion:-1,gameStarted:false,questionActive:false,doublePoints:false,subject:subject};socket.join(`kahoot-host-${pin}`);socket.gamePIN=pin;socket.isKahootHost=true;socket.emit('kahoot-created',{pin,subject});});
  socket.on('kahoot-double',()=>{const pin=socket.gamePIN;if(!pin||!kahootGames[pin])return;kahootGames[pin].doublePoints=true;io.to(`kahoot-host-${pin}`).emit('kahoot-double-active');io.to(`kahoot-${pin}`).emit('kahoot-double-active');});
  socket.on('kahoot-start',()=>{const pin=socket.gamePIN;if(!pin||!kahootGames[pin])return;const g=kahootGames[pin];g.gameStarted=true;g.currentQuestion=0;io.to(`kahoot-${pin}`).emit('kahoot-started');io.to(`kahoot-host-${pin}`).emit('kahoot-started');setTimeout(()=>sendKahootQ(pin),3000);});
  socket.on('kahoot-join',(data)=>{const{pin,nickname}=data;if(!kahootGames[pin]){socket.emit('kahoot-join-error',{message:'Game not found!'});return;}const ep=Object.entries(kahootGames[pin].players).find(([id,p])=>p.nickname===nickname&&id!==socket.id);if(ep){const[oid,od]=ep;kahootGames[pin].players[socket.id]={...od,currentAnswer:null,_basePoints:0,online:true};delete kahootGames[pin].players[oid];socket.join(`kahoot-${pin}`);socket.gamePIN=pin;socket.isKahootPlayer=true;socket.emit('kahoot-join-success',{pin,nickname,character:od.character,color:od.color,reconnect:true});io.to(`kahoot-host-${pin}`).emit('kahoot-player-joined',{players:getKahootPlayers(pin),count:Object.values(kahootGames[pin].players).filter(p=>p.online!==false).length});if(kahootGames[pin].gameStarted&&kahootGames[pin].questionActive){const g=kahootGames[pin],q=g.questions[g.currentQuestion];socket.emit('kahoot-started');socket.emit('kahoot-question',{questionNumber:g.currentQuestion+1,totalQuestions:30,questionText:q.q,answers:q.a});}}else{if(kahootGames[pin].gameStarted){socket.emit('kahoot-join-error',{message:'Game already started!'});return;}kahootGames[pin].players[socket.id]={nickname:nickname||'Player',character:data.character||'😊',color:data.color||'#e94560',score:0,streak:0,currentAnswer:null,_basePoints:0,online:true};socket.join(`kahoot-${pin}`);socket.gamePIN=pin;socket.isKahootPlayer=true;io.to(`kahoot-host-${pin}`).emit('kahoot-player-joined',{players:getKahootPlayers(pin),count:Object.keys(kahootGames[pin].players).length});socket.emit('kahoot-join-success',{pin,nickname,character:data.character,color:data.color});}});
  socket.on('kahoot-answer',(data)=>{const pin=socket.gamePIN;if(!pin||!kahootGames[pin])return;const g=kahootGames[pin],p=g.players[socket.id];if(!p||!g.questionActive||p.currentAnswer!==null)return;const ans=parseInt(data.answer),q=g.questions[g.currentQuestion],isCorrect=(ans===q.c),timeElapsed=(Date.now()-g.questionStartTime)/1000;let pts=0;if(isCorrect){const ratio=Math.max(0,1-(timeElapsed/20));pts=Math.floor(1000*ratio);if(pts<250)pts=250;}else{p.streak=0;}p._basePoints=pts;p.score+=pts;p.currentAnswer=ans;socket.emit('kahoot-answer-result',{correct:isCorrect,points:pts,totalScore:p.score,streak:p.streak,double:g.doublePoints});});
  socket.on('kahoot-next',()=>{const pin=socket.gamePIN;if(!pin||!kahootGames[pin])return;const g=kahootGames[pin];g.currentQuestion++;if(g.currentQuestion>=30){endKahoot(pin);return;}sendKahootQ(pin);});
  function sendKahootQ(pin){const g=kahootGames[pin];if(!g)return;const qi=g.currentQuestion,q=g.questions[qi];Object.keys(g.players).forEach(id=>{g.players[id].currentAnswer=null;g.players[id]._basePoints=0;});g.doublePoints=false;g.questionActive=true;g.questionStartTime=Date.now();io.to(`kahoot-host-${pin}`).emit('kahoot-question',{questionNumber:qi+1,totalQuestions:30,questionText:q.q,answers:q.a});io.to(`kahoot-${pin}`).emit('kahoot-question',{questionNumber:qi+1,totalQuestions:30,questionText:q.q,answers:q.a});setTimeout(()=>{if(g.questionActive)endKahootQ(pin);},20000);}
  function endKahootQ(pin){const g=kahootGames[pin];if(!g||!g.questionActive)return;g.questionActive=false;if(g.doublePoints){Object.values(g.players).forEach(p=>{if(p._basePoints>0&&p.currentAnswer!==null){p.score+=p._basePoints;p._basePoints=0;}});}const lb=getKahootLeaderboard(pin);io.to(`kahoot-host-${pin}`).emit('kahoot-results',{leaderboard:lb});io.to(`kahoot-${pin}`).emit('kahoot-results',{leaderboard:lb});}
  function endKahoot(pin){const g=kahootGames[pin];if(!g)return;const lb=getKahootLeaderboard(pin);io.to(`kahoot-host-${pin}`).emit('kahoot-ended',{leaderboard:lb});io.to(`kahoot-${pin}`).emit('kahoot-ended',{leaderboard:lb});}
  function getKahootPlayers(pin){const g=kahootGames[pin];if(!g)return[];return Object.entries(g.players).map(([id,p])=>({id,nickname:p.nickname,character:p.character,color:p.color,score:p.score,online:p.online!==false}));}
  function getKahootLeaderboard(pin){const g=kahootGames[pin];if(!g)return[];return Object.entries(g.players).map(([id,p])=>({nickname:p.nickname,character:p.character,color:p.color,score:p.score,streak:p.streak,online:p.online!==false})).sort((a,b)=>b.score-a.score);}

  socket.on('disconnect',()=>{const qc=socket.quizCode,gc=socket.gamePIN;if(qc&&quizSessions[qc]){if(socket.isQuizHost){io.to(`quiz-${qc}`).emit('host-disconnected');delete quizSessions[qc];}else if(quizSessions[qc].players[socket.id]){quizSessions[qc].players[socket.id].loggedIn=false;io.to(`quiz-host-${qc}`).emit('quiz-scores-update',{scores:getScores(qc)});}}if(gc&&kahootGames[gc]){if(socket.isKahootHost){io.to(`kahoot-${gc}`).emit('kahoot-host-disconnected');delete kahootGames[gc];}else if(kahootGames[gc].players[socket.id]){kahootGames[gc].players[socket.id].online=false;io.to(`kahoot-host-${gc}`).emit('kahoot-player-left',{players:getKahootPlayers(gc),count:Object.values(kahootGames[gc].players).filter(p=>p.online!==false).length});}}});
});

const PORT=process.env.PORT||3000;
server.listen(PORT,'0.0.0.0',()=>console.log(`Server on port ${PORT}`));